### ISSUE TITLE
Soft Launch ignition absolute timing is unsigned

### ISSUE THREAD

**Issue by noisymime** [speeduino/speeduino#1188]
The soft launch absolute timing setting allows for negative advance values (S08 in the ini) however `correctionSoftLaunch()` uses a byte to store the temporary value. 

Need to review all ignition corrections functions to make sure the same problem is not happening elsewhere

**Comment by adbancroft** [comment]
> The soft launch absolute timing setting allows for negative advance values (S08 in the ini) however correctionSoftLaunch() uses a byte to store the temporary value.

PR #1207 covers this case: the code works correctly as-is. 

> Need to review all ignition corrections functions to make sure the same problem is not happening elsewhere

I have a follow up PR ready to go that does exactly that (along with a huge speedup).
