### ISSUE TITLE
Crash/Misfire only with 202402 Firmware

### ISSUE THREAD

**Issue by zacharyneveu** [speeduino/speeduino#1205]
I upgraded from the 202207.2 firmware to the 202402 firmware and I'm seeing a strange issue. Downgrading back to the 202207.2 firmware resolves the issue so I believe it's an issue with the new firmware. The engine has been running on the 202207.2 firmware for a full season of racing with no issues, so I'm confident this isn't a hardware issue.

# Issue Description
After running fine for several minutes the engine suddenly hits a chronic misfire - it sounds like at least 2 of 4 cylinders stop firing, the engine can barely hold 1kRPM at full throttle and AFR goes to full lean. If I kill the engine it will not restart. If I power cycle the ECU though the issue resolves itself immediately and the engine starts fine. Looking at logs of the issue I'm not seeing any sync loss, errors, drops in loops/rev or anything else concerning, the AFR just goes very lean and revs drop.

# Setup
Board: 0.4.4d from WTMTronics
Engine: Lancia twin-cam, 1.8l 4 cylinder with a turbo
TunerStudio Accessories used: tach output, boost control, DFCO

I can't spend too much time running the bugged tune, but happy to help debug however I can. 

# Log Screenshot
This shows the log I captured of one of the crashes. The cursor is over the moment I think it happened, although it's a little hard to tell because DFCO triggered and the AFR just never came back down when DFCO turned off. Can upload tune and log but GitHub doesn't seem to like those.
<img width="1514" alt="image" src="https://github.com/noisymime/speeduino/assets/23347363/d54da04d-a2f1-4ff6-93e4-5d5cf3b79cec">

**Comment by zacharyneveu** [comment]
Looking at the 202402 changelog I noticed the DFCO taper feature was added. I have that disabled (DFCO settings in screenshot below). Looking at the code, it looks like the DFCO logic should remain about the same with this disabled, so not sure if that is a likely culprit.
<img width="683" alt="image" src="https://github.com/noisymime/speeduino/assets/23347363/8b70c557-bb86-4bac-8480-4ba82cff98e6">

**Comment by ggurov** [comment]
upload tune and log to https://tunes.speeduino.com/

**Comment by noisymime** [comment]
As mentioned, please pot your tune at the above site. 

Haven't seen any other reports of similar behaviour, but with the tune I can see if I can reproduce on the bench

**Comment by noisymime** [comment]
Closing as no followup details provided
