### ISSUE TITLE
Pin 14 is Always being pullup

### ISSUE THREAD

**Issue by FazxFi** [speeduino/speeduino#1206]
Is pin 14 on Mega2560 is intended to always has 5V on them?

**Comment by noisymime** [comment]
What board are you using / have selected in the tune? 

The function of each pin is dictated by the board in use.

**Comment by FazxFi** [comment]
I encounter this is went was testing my custom board ,so I firstly thought that its an error on my definition, but I don,t see anything wrong, so I tried v0.4 board but it still had that problem and also happen on another mega that is only on v0.4 board

I haven't change anything, its a clean tune and untouch latest firmware.(maybe not but still the pinout is not being touch)
