### ISSUE TITLE
Missing tooth decoder works with single tooth cam, but code says it doesn't

### ISSUE THREAD

**Issue by clytle374** [speeduino/speeduino#1257]
Maybe I'm really making a mistake here, but it seems that the "missing tooth" setting in tuner studio works with a crank wheel and single tooth cam sensor.  This is "missingtooth" in the speeduino code, I'm pretty sure it is anyway. But the following code comment above missing tooth has me confused.  What am I misunderstanding?  

  
`/** A (single) multi-tooth wheel with one of more 'missing' teeth.
* The first tooth after the missing one is considered number 1 and is the basis for the trigger angle.
* Note: This decoder does not currently support dual wheel (ie missing tooth + single tooth on cam).
* @defgroup dec_miss Missing tooth wheel
* @{`

**Comment by MykkHan928** [comment]
Further down the code on line 519 it has checks if sequential is chosen and then it looks for the secondary trigger. The original note is probably left over from using only a crank speed missing tooth trigger with no secondary for paired cylinder and waste spark.

**Comment by clytle374** [comment]
I kinda assumed as much, just wanted confirmation and a note it can be deleted.
